analyze_video:
  name: Analyze Video
  description: Analyze a video file using Gemini AI
  fields:
    camera:
      name: Camera
      description: The name of the camera that recorded the video
      required: true
      example: "front_yard"
      selector:
        text:
    video_path:
      name: Video Path
      description: Full path to the video file
      required: true
      example: "/media/frigate/front_yard/clips/2025-01/19/10-05-15.mp4"
      selector:
        text:
